Metrics/LineLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  MinNameLength: 0

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
